#ifndef MIDI_LUT
#define MIDI_LUT

/// Table I & II
#define STATUS_BYTE_NOTE_OFF            0x80
#define STATUS_BYTE_NOTE_ON             0x90
#define STATUS_BYTE_KEY_AFTERTOUCH      0xA0
#define STATUS_BYTE_CONTROL_CHANGE      0xB0
#define STATUS_BYTE_PROGRAM_CHANGE      0xC0
#define STATUS_BYTE_CHANNEL_AFTERTOUCH  0xD0
#define STATUS_BYTE_PITCH_BEND          0xE0
#define STATUS_BYTE_SYSTEM_MESSAGE      0xF0
#define STATUS_BYTE_MASK                0xF0
#define STATUS_BYTE_CHANNEL_MASK        0x0F

/// Table III
#define CONTROLLER_BYTE_BANK_SELECT     0x00
#define CONTROLLER_BYTE_MOD_WHEEL       0x01
#define CONTROLLER_BYTE_BREATH_CTL      0x02
#define CONTROLLER_BYTE_FOOT_CTL        0x04
#define CONTROLLER_BYTE_PORTAMENTO_TIME 0x05
#define CONTROLLER_BYTE_DATA_MSB        0x06
#define CONTROLLER_BYTE_CHANNEL_VOL     0x07
#define CONTROLLER_BYTE_BALANCE         0x08
#define CONTROLLER_BYTE_PAN             0x0A
#define CONTROLLER_BYTE_EXPRESSION_CTL  0x0B
#define CONTROLLER_BYTE_EFFECT_CTL_1    0x0C
#define CONTROLLER_BYTE_EFFECT_CTL_2    0x0D
#define CONTROLLER_BYTE_GP_CTL_01       0x10
#define CONTROLLER_BYTE_GP_CTL_02       0x11
#define CONTROLLER_BYTE_GP_CTL_03       0x12
#define CONTROLLER_BYTE_GP_CTL_04       0x13
#define CONTROLLER_BYTE_DAMPER_PEDAL    0x40
#define CONTROLLER_BYTE_PORTAMENTO_TOGGLE 0x41
#define CONTROLLER_BYTE_SOSTENUTO       0x42
#define CONTROLLER_BYTE_SOFT_PEDAL      0x43
#define CONTROLLER_BYTE_LEGATO_SWITCH   0x44
#define CONTROLLER_BYTE_HOLD_2          0x45
#define CONTROLLER_BYTE_SOUND_CTL_1     0x46
#define CONTROLLER_BYTE_SOUND_CTL_2     0x47
#define CONTROLLER_BYTE_SOUND_CTL_3     0x48
#define CONTROLLER_BYTE_SOUND_CTL_4     0x49
#define CONTROLLER_BYTE_SOUND_CTL_5     0x4A
#define CONTROLLER_BYTE_SOUND_CTL_6     0x4B
#define CONTROLLER_BYTE_SOUND_CTL_7     0x4C
#define CONTROLLER_BYTE_SOUND_CTL_8     0x4D
#define CONTROLLER_BYTE_SOUND_CTL_9     0x4E
#define CONTROLLER_BYTE_SOUND_CTL_10    0x4F
#define CONTROLLER_BYTE_GP_CTL_05       0x50
#define CONTROLLER_BYTE_GP_CTL_06       0x51
#define CONTROLLER_BYTE_GP_CTL_07       0x52
#define CONTROLLER_BYTE_GP_CTL_08       0x53
#define CONTROLLER_BYTE_PORTAMENTO_CTL  0x54
#define CONTROLLER_BYTE_EFFECT_1_DEPTH  0x5B
#define CONTROLLER_BYTE_EFFECT_2_DEPTH  0x5C
#define CONTROLLER_BYTE_EFFECT_3_DEPTH  0x5D
#define CONTROLLER_BYTE_EFFECT_4_DEPTH  0x5E
#define CONTROLLER_BYTE_EFFECT_5_DEPTH  0x5F
#define CONTROLLER_BYTE_DATA_INCREMENT  0x60
#define CONTROLLER_BYTE_DATA_DECREMENT  0x61
#define CONTROLLER_BYTE_NONREG_PARAM_LSB    0x62
#define CONTROLLER_BYTE_NONREG_PARAM_MSB    0x63
#define CONTROLLER_BYTE_REG_PARAM_LSB       0x64
#define CONTROLLER_BYTE_REG_PARAM_MSB       0x65

/// Table IIIa
#define PITCH_BEND_SENSITIVITY_PARAM_MSB  0x00
#define FINE_TUNING_PARAM_MSB             0x00
#define COARSE_TUNING_PARAM_MSB           0x00
#define TUNING_PROGRAM_SELECT_PARAM_MSB   0x00
#define TUNING_BANK_SELECT_PARAM_MSB      0x00
#define PITCH_BEND_SENSITIVITY_PARAM_LSB  0x00
#define FINE_TUNING_PARAM_LSB             0x01
#define COARSE_TUNING_PARAM_LSB           0x02
#define TUNING_PROGRAM_SELECT_PARAM_LSB   0x03
#define TUNING_BANK_SELECT_PARAM_LSB      0x04

/// Table IV
#define CONTROL_CHANGE_DATA_BYTE_MASK   0xF8
#define CONTROL_CHANGE
#define CHANNEL_MODE_ALL_SOUND_OFF      120
#define CHANNEL_MODE_RESET_ALL_CTLS     121
#define CHANNEL_MODE_LOCAL_CONTROL      122
#define CHANNEL_MODE_LOCAL_CONTROL_OFF  0
#define CHANNEL_MODE_LOCAL_CONTROL_ON   127
#define CHANNEL_MODE_ALL_NOTES_OFF      123
#define CHANNEL_MODE_OMNI_MODE_OFF      124
#define CHANNEL_MODE_OMNI_MODE_ON       125
#define CHANNEL_MODE_MONO_MODE_ON       126
#define CHANNEL_MODE_POLY_MODE_ON       127

/// Table V
#define SYSTEM_MSG_MIDI_TIMECODE  0xF1
#define SYSTEM_MSG_SONG_POSITION  0xF2
#define SYSTEM_MSG_SONG_SELECT    0xF3
#define SYSTEM_MSG_TUNE_REQUEST   0xF6
#define SYSTEM_MSG_EOX            0xF7

/// Table VI
#define SYSTEM_RT_MSG_TIMING_CLK      0xF8
#define SYSTEM_RT_MSG_START           0xFA
#define SYSTEM_RT_MSG_CONTINUE        0xFB
#define SYSTEM_RT_MSG_STOP            0xFC
#define SYSTEM_RT_MSG_ACTIVE_SENSING  0xFE
#define SYSTEM_RT_MSG_SYSTEM_RESET    0xFF

/// Table VIIa
#define NON_RT_TIMECODE_SPECIAL               0x0400
#define NON_RT_TIMECODE_PUNCH_IN_PTS          0x0401
#define NON_RT_TIMECODE_PUNCH_OUT_PTS         0x0402
#define NON_RT_TIMECODE_DEL_PUNCH_IN          0x0403
#define NON_RT_TIMECODE_DEL_PUNCH_OUT         0x0404
#define NON_RT_TIMECODE_EVENT_START_PT        0x0405
#define NON_RT_TIMECODE_EVENT_STOP_PT         0x0406
#define NON_RT_TIMECODE_EVENT_START_PT_INFO   0x0407
#define NON_RT_TIMECODE_EVENT_STOP_PT_INFO    0x0408
#define NON_RT_TIMECODE_DEL_EVENT_START       0x0409
#define NON_RT_TIMECODE_DEL_EVEN_STOP         0x040A
#define NON_RT_TIMECODE_CUE_POINTS            0x040B
#define NON_RT_TIMECODE_CUE_POINTS_INFO       0x040C
#define NON_RT_TIMECODE_DEL_CUE_POINT         0x040D
#define NON_RT_TIMECODE_EVENT_NAME_INFO       0x040E
#define NON_RT_MULTIPLE_LOOP_PTS              0x0501
#define NON_RT_LOOP_PTS_REQUEST               0x0502
#define NON_RT_IDENTITY_REQUEST               0x0601
#define NON_RT_IDENTITY_REPLY                 0x0602
#define NON_RT_FILEDUMP_HEADER                0x0701
#define NON_RT_FILEDUMP_DATA_PACKET           0x0702
#define NON_RT_FILEDUMP_REQUEST               0x0703
#define NON_RT_MIDI_BULK_DUMP_REQUEST         0x0800
#define NON_RT_MIDI_BULK_DUMP_REPLY           0x0801
#define NON_RT_MIDI_SYSTEM_ON                 0x0901
#define NON_RT_MIDI_SYSTEM_OFF                0x0902

#endif
